server:
  port: 7001
eureka:
  instance:
    hostname: ek1.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ek2.com:7002/eureka/
spring:
  application:
    name: EurekaServer